// resources/js/pages/admin/NotificationSettings.vue
<template>
    <div class="notification-settings-page">
        <div class="mb-6">
            <h1 class="text-2xl font-bold text-foreground flex items-center gap-2">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
                </svg>
                Настройки уведомлений заказов
            </h1>
            <p class="text-muted-foreground mt-1">
                Управление уведомлениями при создании и обработке заказов
            </p>
        </div>

        <!-- Загрузка -->
        <div v-if="loading && !settings.length" class="bg-card rounded-lg border border-border p-12 text-center">
            <p class="text-muted-foreground">Загрузка настроек...</p>
        </div>

        <!-- Ошибка -->
        <div v-else-if="error" class="bg-destructive/10 border border-destructive/20 rounded-lg p-4">
            <p class="text-destructive">{{ error }}</p>
        </div>

        <!-- Настройки -->
        <div v-else class="space-y-6">
            <div v-for="setting in settings" :key="setting.event" class="bg-card rounded-lg border border-border p-6">
                <div class="flex items-center justify-between mb-4">
                    <div>
                        <h2 class="text-lg font-semibold text-foreground">{{ getEventLabel(setting.event).title }}</h2>
                        <p class="text-sm text-muted-foreground mt-1">{{ getEventLabel(setting.event).description }}</p>
                    </div>
                    <div class="flex items-center gap-2">
                        <label class="text-sm">Включено</label>
                        <input
                            type="checkbox"
                            v-model="setting.enabled"
                            @change="updateSetting(setting.event, { enabled: setting.enabled })"
                            class="w-4 h-4"
                        />
                    </div>
                </div>

                <div class="space-y-4">
                    <!-- Шаблон сообщения -->
                    <div>
                        <label class="block text-sm font-medium text-foreground mb-1">
                            Шаблон сообщения
                        </label>
                        <textarea
                            v-model="setting.message_template"
                            @blur="updateSetting(setting.event, { message_template: setting.message_template || null })"
                            placeholder="Используйте {order_id} для подстановки номера заказа"
                            class="w-full min-h-[100px] px-3 py-2 rounded-lg border border-input bg-background text-foreground"
                        ></textarea>
                        <p class="text-xs text-muted-foreground mt-1">
                            Плейсхолдеры: {'{order_id}'}, {'{amount}'} и другие
                        </p>
                    </div>

                    <!-- Support Chat ID (только для order_accepted_client) -->
                    <div v-if="setting.event === 'order_accepted_client'">
                        <label class="block text-sm font-medium text-foreground mb-1">
                            ID чата поддержки (Telegram ID администратора или username)
                        </label>
                        <input
                            v-model="setting.support_chat_id"
                            @blur="updateSetting(setting.event, { support_chat_id: setting.support_chat_id || null })"
                            placeholder="Например: 123456789 или @username"
                            class="w-full h-10 px-3 rounded-lg border border-input bg-background text-foreground"
                        />
                        <p class="text-xs text-muted-foreground mt-1">
                            Если не указан, будет использован первый администратор бота
                        </p>
                    </div>

                    <!-- Кнопки -->
                    <div>
                        <div class="flex items-center justify-between mb-2">
                            <label class="block text-sm font-medium text-foreground">Кнопки</label>
                            <button
                                type="button"
                                @click="addButtonRow(setting)"
                                class="h-8 px-3 text-sm bg-accent/10 text-accent rounded-lg hover:bg-accent/20"
                            >
                                + Добавить строку
                            </button>
                        </div>

                        <div v-if="setting.buttons && setting.buttons.length > 0" class="space-y-3">
                            <div v-for="(row, rowIndex) in setting.buttons" :key="rowIndex" class="border rounded-lg p-4 space-y-3">
                                <div class="flex items-center justify-between mb-2">
                                    <span class="text-sm font-medium">Строка {{ rowIndex + 1 }}</span>
                                    <button
                                        type="button"
                                        @click="removeButtonRow(setting, rowIndex)"
                                        class="text-destructive hover:text-destructive/80"
                                    >
                                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                                        </svg>
                                    </button>
                                </div>
                                <div class="space-y-2">
                                    <div v-for="(button, buttonIndex) in row" :key="buttonIndex" class="flex gap-2 items-end">
                                        <div class="flex-1">
                                            <label class="text-xs">Текст кнопки</label>
                                            <input
                                                v-model="button.text"
                                                @blur="updateSetting(setting.event, { buttons: setting.buttons })"
                                                placeholder="Текст кнопки"
                                                class="w-full h-10 px-3 rounded-lg border border-input bg-background text-foreground mt-1"
                                            />
                                        </div>
                                        <div class="w-32">
                                            <label class="text-xs">Тип</label>
                                            <select
                                                v-model="button.type"
                                                @change="updateSetting(setting.event, { buttons: setting.buttons })"
                                                class="w-full h-10 px-3 rounded-lg border border-input bg-background text-foreground mt-1"
                                            >
                                                <option value="callback">Callback</option>
                                                <option value="open_chat">Открыть чат</option>
                                                <option value="open_url">Открыть URL</option>
                                            </select>
                                        </div>
                                        <div class="flex-1">
                                            <label class="text-xs">
                                                {{ button.type === 'callback' ? 'Callback Data' : 
                                                   button.type === 'open_chat' ? 'Значение (support)' : 
                                                   'URL' }}
                                            </label>
                                            <input
                                                v-model="button.value"
                                                @blur="updateSetting(setting.event, { buttons: setting.buttons })"
                                                :placeholder="button.type === 'callback' ? 'order_admin_action:{order_id}:accept' :
                                                              button.type === 'open_chat' ? 'support' :
                                                              'https://example.com'"
                                                class="w-full h-10 px-3 rounded-lg border border-input bg-background text-foreground mt-1"
                                            />
                                        </div>
                                        <button
                                            type="button"
                                            @click="removeButton(setting, rowIndex, buttonIndex)"
                                            class="text-destructive hover:text-destructive/80"
                                        >
                                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                                            </svg>
                                        </button>
                                    </div>
                                    <button
                                        type="button"
                                        @click="addButton(setting, rowIndex)"
                                        class="w-full h-8 px-3 text-sm bg-accent/10 text-accent rounded-lg hover:bg-accent/20"
                                    >
                                        + Добавить кнопку
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div v-else class="border border-dashed rounded-lg p-4 text-center">
                            <p class="text-sm text-muted-foreground mb-2">Кнопки не настроены</p>
                            <button
                                type="button"
                                @click="addButtonRow(setting)"
                                class="h-8 px-3 text-sm bg-accent/10 text-accent rounded-lg hover:bg-accent/20"
                            >
                                + Добавить кнопки
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios';

const EVENT_LABELS = {
    order_created_client: {
        title: 'Уведомление клиенту при создании заказа',
        description: 'Отправляется сразу после создания заказа (статус: new)',
    },
    order_created_admin: {
        title: 'Уведомление администратору при создании заказа',
        description: 'Отправляется администраторам при создании нового заказа',
    },
    order_accepted_client: {
        title: 'Уведомление клиенту при принятии заказа',
        description: 'Отправляется клиенту после того, как администратор принял заказ',
    },
};

export default {
    name: 'NotificationSettings',
    data() {
        return {
            settings: [],
            loading: false,
            error: null,
        };
    },
    mounted() {
        this.loadSettings();
    },
    methods: {
        async loadSettings() {
            try {
                this.loading = true;
                this.error = null;
                const response = await axios.get('/api/v1/notification-settings');
                this.settings = response.data.data || [];
            } catch (error) {
                console.error('Error loading notification settings:', error);
                this.error = 'Ошибка при загрузке настроек уведомлений';
            } finally {
                this.loading = false;
            }
        },
        async updateSetting(event, updates) {
            try {
                await axios.put(`/api/v1/notification-settings/${event}`, updates);
                // Обновление уже произошло через v-model, просто показываем уведомление
                this.$toast?.success('Настройки успешно сохранены');
            } catch (error) {
                console.error('Error updating notification setting:', error);
                this.$toast?.error(error.response?.data?.message || 'Ошибка при сохранении настроек');
            }
        },
        getEventLabel(event) {
            return EVENT_LABELS[event] || { title: event, description: '' };
        },
        addButtonRow(setting) {
            if (!setting.buttons) {
                this.$set(setting, 'buttons', []);
            }
            setting.buttons.push([]);
            this.updateSetting(setting.event, { buttons: setting.buttons });
        },
        removeButtonRow(setting, rowIndex) {
            setting.buttons.splice(rowIndex, 1);
            if (setting.buttons.length === 0) {
                setting.buttons = null;
            }
            this.updateSetting(setting.event, { buttons: setting.buttons });
        },
        addButton(setting, rowIndex) {
            if (!setting.buttons[rowIndex]) {
                this.$set(setting.buttons, rowIndex, []);
            }
            setting.buttons[rowIndex].push({
                text: '',
                type: 'callback',
                value: '',
            });
            this.updateSetting(setting.event, { buttons: setting.buttons });
        },
        removeButton(setting, rowIndex, buttonIndex) {
            setting.buttons[rowIndex].splice(buttonIndex, 1);
            if (setting.buttons[rowIndex].length === 0) {
                setting.buttons.splice(rowIndex, 1);
            }
            if (setting.buttons.length === 0) {
                setting.buttons = null;
            }
            this.updateSetting(setting.event, { buttons: setting.buttons });
        },
    },
};
</script>

// frontend/src/pages/admin/NotificationSettings.tsx
import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Loader2, Bell, Plus, Trash2, Save } from 'lucide-react';
import { toast } from 'sonner';
import { notificationSettingsAPI } from '@/api';

interface ButtonConfig {
  text: string;
  type: 'callback' | 'open_chat' | 'open_url';
  value: string;
}

interface NotificationSetting {
  id: number;
  event: string;
  enabled: boolean;
  message_template: string | null;
  buttons: ButtonConfig[][] | null;
  support_chat_id: string | null;
}

const EVENT_LABELS: Record<string, { title: string; description: string }> = {
  order_created_client: {
    title: 'Уведомление клиенту при создании заказа',
    description: 'Отправляется сразу после создания заказа (статус: new)',
  },
  order_created_admin: {
    title: 'Уведомление администратору при создании заказа',
    description: 'Отправляется администраторам при создании нового заказа',
  },
  order_accepted_client: {
    title: 'Уведомление клиенту при принятии заказа',
    description: 'Отправляется клиенту после того, как администратор принял заказ',
  },
};

export function NotificationSettings() {
  const [isLoading, setIsLoading] = useState(false);
  const [isLoadingData, setIsLoadingData] = useState(true);
  const [settings, setSettings] = useState<NotificationSetting[]>([]);
  const [errors, setErrors] = useState<Record<string, any>>({});

  useEffect(() => {
    loadSettings();
  }, []);

  const loadSettings = async () => {
    try {
      setIsLoadingData(true);
      const data = await notificationSettingsAPI.getAll();
      setSettings(data || []);
    } catch (error: any) {
      console.error('Error loading notification settings:', error);
      toast.error('Ошибка при загрузке настроек уведомлений');
    } finally {
      setIsLoadingData(false);
    }
  };

  const handleUpdate = async (event: string, updates: Partial<NotificationSetting>) => {
    try {
      setIsLoading(true);
      const updated = await notificationSettingsAPI.update(event, updates);
      
      setSettings(prev => prev.map(s => 
        s.event === event ? { ...s, ...updated } : s
      ));
      
      toast.success('Настройки успешно сохранены');
      setErrors({});
    } catch (error: any) {
      console.error('Error updating notification setting:', error);
      const errorData = error?.response?.data;
      if (errorData?.errors) {
        setErrors(prev => ({ ...prev, [event]: errorData.errors }));
      }
      toast.error(errorData?.message || 'Ошибка при сохранении настроек');
    } finally {
      setIsLoading(false);
    }
  };

  const addButton = (event: string, rowIndex: number) => {
    const setting = settings.find(s => s.event === event);
    if (!setting) return;

    const newButtons = setting.buttons ? [...setting.buttons] : [];
    if (!newButtons[rowIndex]) {
      newButtons[rowIndex] = [];
    }
    newButtons[rowIndex].push({
      text: '',
      type: 'callback',
      value: '',
    });

    handleUpdate(event, { buttons: newButtons });
  };

  const removeButton = (event: string, rowIndex: number, buttonIndex: number) => {
    const setting = settings.find(s => s.event === event);
    if (!setting || !setting.buttons) return;

    const newButtons = setting.buttons.map((row, idx) => 
      idx === rowIndex ? row.filter((_, btnIdx) => btnIdx !== buttonIndex) : row
    ).filter(row => row.length > 0);

    handleUpdate(event, { buttons: newButtons.length > 0 ? newButtons : null });
  };

  const updateButton = (event: string, rowIndex: number, buttonIndex: number, updates: Partial<ButtonConfig>) => {
    const setting = settings.find(s => s.event === event);
    if (!setting || !setting.buttons) return;

    const newButtons = setting.buttons.map((row, idx) => 
      idx === rowIndex 
        ? row.map((btn, btnIdx) => 
            btnIdx === buttonIndex ? { ...btn, ...updates } : btn
          )
        : row
    );

    handleUpdate(event, { buttons: newButtons });
  };

  const addButtonRow = (event: string) => {
    const setting = settings.find(s => s.event === event);
    if (!setting) return;

    const newButtons = setting.buttons ? [...setting.buttons, []] : [[]];
    handleUpdate(event, { buttons: newButtons });
  };

  const removeButtonRow = (event: string, rowIndex: number) => {
    const setting = settings.find(s => s.event === event);
    if (!setting || !setting.buttons) return;

    const newButtons = setting.buttons.filter((_, idx) => idx !== rowIndex);
    handleUpdate(event, { buttons: newButtons.length > 0 ? newButtons : null });
  };

  if (isLoadingData) {
    return (
      <div className="p-4 lg:p-8 flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="p-4 lg:p-8">
      <div className="mb-6 lg:mb-8">
        <h1 className="text-2xl lg:text-3xl font-bold text-foreground flex items-center gap-2">
          <Bell className="h-6 w-6" />
          Настройки уведомлений заказов
        </h1>
        <p className="mt-1 text-muted-foreground">
          Управление уведомлениями при создании и обработке заказов
        </p>
      </div>

      <div className="space-y-6">
        {settings.map((setting) => {
          const eventInfo = EVENT_LABELS[setting.event] || {
            title: setting.event,
            description: '',
          };

          return (
            <Card key={setting.event}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>{eventInfo.title}</CardTitle>
                    <CardDescription className="mt-1">
                      {eventInfo.description}
                    </CardDescription>
                  </div>
                  <div className="flex items-center gap-2">
                    <Label htmlFor={`enabled-${setting.event}`} className="text-sm">
                      Включено
                    </Label>
                    <Switch
                      id={`enabled-${setting.event}`}
                      checked={setting.enabled}
                      onCheckedChange={(checked) => 
                        handleUpdate(setting.event, { enabled: checked })
                      }
                    />
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Шаблон сообщения */}
                <div>
                  <Label htmlFor={`template-${setting.event}`}>
                    Шаблон сообщения
                  </Label>
                  <Textarea
                    id={`template-${setting.event}`}
                    value={setting.message_template || ''}
                    onChange={(e) => 
                      handleUpdate(setting.event, { message_template: e.target.value || null })
                    }
                    placeholder="Используйте {order_id} для подстановки номера заказа"
                    className="mt-1 min-h-[100px]"
                  />
                  <p className="text-xs text-muted-foreground mt-1">
                    Плейсхолдеры: {'{order_id}'}, {'{amount}'} и другие
                  </p>
                </div>

                {/* Support Chat ID (только для order_accepted_client) */}
                {setting.event === 'order_accepted_client' && (
                  <div>
                    <Label htmlFor={`support-${setting.event}`}>
                      ID чата поддержки (Telegram ID администратора или username)
                    </Label>
                    <Input
                      id={`support-${setting.event}`}
                      value={setting.support_chat_id || ''}
                      onChange={(e) => 
                        handleUpdate(setting.event, { support_chat_id: e.target.value || null })
                      }
                      placeholder="Например: 123456789 или @username"
                      className="mt-1"
                    />
                    <p className="text-xs text-muted-foreground mt-1">
                      Если не указан, будет использован первый администратор бота
                    </p>
                  </div>
                )}

                {/* Кнопки */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <Label>Кнопки</Label>
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => addButtonRow(setting.event)}
                    >
                      <Plus className="h-4 w-4 mr-1" />
                      Добавить строку
                    </Button>
                  </div>

                  {setting.buttons && setting.buttons.length > 0 ? (
                    <div className="space-y-3">
                      {setting.buttons.map((row, rowIndex) => (
                        <div key={rowIndex} className="border rounded-lg p-4 space-y-3">
                          <div className="flex items-center justify-between mb-2">
                            <span className="text-sm font-medium">Строка {rowIndex + 1}</span>
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              onClick={() => removeButtonRow(setting.event, rowIndex)}
                            >
                              <Trash2 className="h-4 w-4 text-destructive" />
                            </Button>
                          </div>
                          <div className="space-y-2">
                            {row.map((button, buttonIndex) => (
                              <div key={buttonIndex} className="flex gap-2 items-end">
                                <div className="flex-1">
                                  <Label className="text-xs">Текст кнопки</Label>
                                  <Input
                                    value={button.text}
                                    onChange={(e) => 
                                      updateButton(setting.event, rowIndex, buttonIndex, { text: e.target.value })
                                    }
                                    placeholder="Текст кнопки"
                                    className="mt-1"
                                  />
                                </div>
                                <div className="w-32">
                                  <Label className="text-xs">Тип</Label>
                                  <select
                                    value={button.type}
                                    onChange={(e) => 
                                      updateButton(setting.event, rowIndex, buttonIndex, { 
                                        type: e.target.value as ButtonConfig['type'] 
                                      })
                                    }
                                    className="w-full h-10 px-3 rounded-lg border border-input bg-background text-foreground mt-1"
                                  >
                                    <option value="callback">Callback</option>
                                    <option value="open_chat">Открыть чат</option>
                                    <option value="open_url">Открыть URL</option>
                                  </select>
                                </div>
                                <div className="flex-1">
                                  <Label className="text-xs">
                                    {button.type === 'callback' ? 'Callback Data' : 
                                     button.type === 'open_chat' ? 'Значение (support)' : 
                                     'URL'}
                                  </Label>
                                  <Input
                                    value={button.value}
                                    onChange={(e) => 
                                      updateButton(setting.event, rowIndex, buttonIndex, { value: e.target.value })
                                    }
                                    placeholder={
                                      button.type === 'callback' ? 'order_admin_action:{order_id}:accept' :
                                      button.type === 'open_chat' ? 'support' :
                                      'https://example.com'
                                    }
                                    className="mt-1"
                                  />
                                </div>
                                <Button
                                  type="button"
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => removeButton(setting.event, rowIndex, buttonIndex)}
                                >
                                  <Trash2 className="h-4 w-4 text-destructive" />
                                </Button>
                              </div>
                            ))}
                            <Button
                              type="button"
                              variant="outline"
                              size="sm"
                              onClick={() => addButton(setting.event, rowIndex)}
                              className="w-full"
                            >
                              <Plus className="h-4 w-4 mr-1" />
                              Добавить кнопку
                            </Button>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="border border-dashed rounded-lg p-4 text-center">
                      <p className="text-sm text-muted-foreground mb-2">
                        Кнопки не настроены
                      </p>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => addButtonRow(setting.event)}
                      >
                        <Plus className="h-4 w-4 mr-1" />
                        Добавить кнопки
                      </Button>
                    </div>
                  )}

                  {errors[setting.event] && (
                    <Alert variant="destructive" className="mt-2">
                      <AlertDescription>
                        {Object.values(errors[setting.event]).flat().join(', ')}
                      </AlertDescription>
                    </Alert>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
